# WebsiteStaticBundle
static:
   resource: "@WebsiteStaticBundle/Resources/config/routing.yml"

# WebsiteOfficeBundle
office:
    resource: "@WebsiteOfficeBundle/Resources/config/routing.yml"
    prefix:   /office

# WebsiteNewsBundle
news:
   resource: "@WebsiteNewsBundle/Resources/config/routing.yml"
   prefix: /news

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_assetic:
    resource: .
    type:     assetic
