<?php

namespace Website\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
  /**
   * Fetch last $quantity news
   *
   * @param  integer $quantity    How many briefs
   * @return object
   */
  public function fetchLastNews($quantity) {
    return $this->getEntityManager()
           ->createQueryBuilder()
           ->select('p')
           ->from('WebsiteNewsBundle:News', 'p')
           ->where('p.isPublished = 1')
           ->orderBy('p.newsDate', 'DESC')
           ->setFirstResult(0)
           ->setMaxResults($quantity)
           ->getQuery()
           ->getResult();
  }

  public function fetchAllDateDesc() {
    return $this->getEntityManager()
           ->createQueryBuilder()
           ->select('p')
           ->from('WebsiteNewsBundle:News', 'p')
           ->where('p.isPublished = 1')
           ->orderBy('p.newsDate', 'DESC')
           ->getQuery()
           ->getResult();
  }
}