# site main page
homepage:
    pattern:  /
    defaults: { _controller: WebsiteStaticBundle:Static:index }

# tour search
search:
    pattern:  /search
    defaults: { _controller: WebsiteStaticBundle:Static:search }

# about company
about:
    pattern:  /about
    defaults: { _controller: WebsiteStaticBundle:Static:static, name: about }

# useful info
info:
    pattern:  /info
    defaults: { _controller: WebsiteStaticBundle:Static:static, name: info }

# weather@resorts
weather:
    pattern:  /weather
    defaults: { _controller: WebsiteStaticBundle:Static:static, name: weather }

# our team
team:
    pattern:  /team
    defaults: { _controller: WebsiteStaticBundle:Static:static, name: team }

# travel planner
travel_planner:
    pattern:  /travel-planner
    defaults: { _controller: WebsiteStaticBundle:Static:static, name: travel-planner }
    requirements:
        _method: GET

#travel_planner:
#    pattern:  /travel-planner
#    defaults: { _controller: WebsiteStaticBundle:TravelPlanner:index }
#    requirements:
#        _method: GET
#
#travel_planner_submit:
#    pattern:  /travel-planner
#    defaults: { _controller: WebsiteStaticBundle:TravelPlanner:submit }
#    requirements:
#        _method: POST
