parameters:
#    website_news.example.class: Website\NewsBundle\Example

services:
#    website_news.example:
#        class: %website_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
